package io.kory.openai.files.model

import kotlinx.serialization.Serializable
import kotlin.jvm.JvmInline

/**
 * The intended purpose of an uploaded file in the OpenAI Files API.
 *
 * Use the predefined constants for standard purposes, or instantiate with
 * a custom value for non-standard cases.
 *
 * @property value The purpose string sent to the API.
 */
@Serializable
@JvmInline
value class OpenAIPurpose(val value: String) {
    companion object {
        /** File used by the Assistants API. */
        val ASSISTANTS = OpenAIPurpose("assistants")

        /** Output file generated by the Assistants API. */
        val ASSISTANTS_OUTPUT = OpenAIPurpose("assistants_output")

        /** Input file for the Batch API. */
        val BATCH = OpenAIPurpose("batch")

        /** Output file generated by the Batch API. */
        val BATCH_OUTPUT = OpenAIPurpose("batch_output")

        /** File used for fine-tuning. */
        val FINE_TUNE = OpenAIPurpose("fine-tune")

        /** Results generated from a fine-tuning job. */
        val FINE_TUNE_RESULTS = OpenAIPurpose("fine-tune-results")

        /** File used for vision tasks. */
        val VISION = OpenAIPurpose("vision")

        /** User data file. */
        val USER_DATA = OpenAIPurpose("user_data")
    }
}