package io.kory.openai.message.content.audio

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Audio data in an OpenAI assistant message.
 *
 * Present when the audio output modality is requested via
 * `modalities: ["audio"]` with [OpenAIChatCompletionAudioParam].
 *
 * @property id Unique identifier for this audio response. Can be passed back
 * as [OpenAIAssistantAudioParam.id] in a subsequent request to reference
 * a previous audio response in multi-turn conversations.
 * @property data Base64 encoded audio bytes generated by the model, in the format
 * specified in the request. `null` when the payload is not included.
 * @property expiresAt Unix timestamp (in seconds) for when this audio response
 * no longer remains accessible on the server. `null` if not provided.
 * @property transcript Transcript of the audio generated by the model.
 * `null` when no transcript is available.
 *
 * @see io.kory.openai.message.OpenAIMessage.audio
 */
@Serializable
data class OpenAIChatCompletionAudioResponse(
    val id: String,
    val data: String? = null,
    @SerialName("expires_at") val expiresAt: Long? = null,
    val transcript: String? = null,
)

/**
 * Reference to a previous audio response from the model.
 *
 * Used in assistant message parameters to continue a multi-turn
 * audio conversation.
 *
 * @property id Unique identifier for a previous audio response from the model.
 *
 * @see io.kory.openai.message.param.OpenAIMessageParam.Assistant
 */
@Serializable
data class OpenAIAssistantAudioParam(
    val id: String,
)
