package io.kory.openai.message

import io.kory.core.message.Role
import io.kory.openai.message.content.OpenAIChatCompletionContent
import io.kory.openai.message.content.audio.OpenAIChatCompletionAudioResponse
import io.kory.openai.tool.OpenAIFunctionCall
import io.kory.openai.tool.OpenAIToolCall
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OpenAI response message from a chat completion.
 *
 * Example:
 * ```json
 * {
 *   "role": "assistant",
 *   "content": "Hello! How can I help you today?"
 * }
 * ```
 *
 * @property role The role of the message sender.
 * @property content The message content. `null` when the model only returns tool calls.
 * @property reasoningContent Reasoning content (primary field). `null` if not present.
 * @property reasoning Reasoning content (legacy field). `null` if not present.
 * @property refusal The refusal message generated by the model. `null` if the model
 * did not refuse the request.
 * @property audio Audio data when the audio output modality is requested.
 * `null` when the response contains no audio.
 * @property functionCall Deprecated function call, replaced by [toolCalls].
 * `null` when the model did not use legacy function calling.
 * @property toolCalls Tool calls requested by the model. `null` if none.
 */
@Serializable
data class OpenAIMessage(
    val role: Role,
    val content: OpenAIChatCompletionContent? = null,
    @SerialName("reasoning_content") val reasoningContent: String? = null,
    val reasoning: String? = null,
    val refusal: String? = null,
    val audio: OpenAIChatCompletionAudioResponse? = null,
    @SerialName("function_call") val functionCall: OpenAIFunctionCall? = null,
    @SerialName("tool_calls") val toolCalls: List<OpenAIToolCall>? = null
) {
    /**
     * Returns the effective reasoning content, preferring [reasoningContent] over [reasoning].
     *
     * @return The reasoning text, or `null` if neither field is present.
     */
    val effectiveReasoning: String? get() = reasoningContent ?: reasoning
}
